#! /usr/bin/env python

main = {
	"Power" : { "command" : "P1P",
				"response" : "P1P([01])"
				"values" : { "Off" : "0",
							 "On" : "1"} },
	"Source" : { "command" : "P1S" },
				"response" : "P1S([0-9c-j])"
				#values are special for this one
	#TODO: figure out simulcast
	"RecSource" : { "command" : "P4S" },
				"response" : "P4S([0-9c-j])"
				#values are special for this one
	#TODO: figure out simulcast
	"Mute" : { "command" : "P1M",
				"response" : "P1M([01])"
				"values" : {"Off" : "0",
							"On" : "1",
							"Toggle" : "T"} },
	"HeadphoneMute" : { "command" : "HM",
				"response" : "HM([01])"
				"values" : {"Off" : "0",
							"On" : "1",
							"Toggle" : "T"} },
	"MasterVolume" : { "command" : "P1VM",
				"response" : "P1V([+-]\d\d.\d)"
			"min" : -95.5,
			"max" : 31.5},
	"HeadphoneVolume" : { "command" : "HV",
				"response" : "HV([+-]\d\d.\d)"
			"min" : -62.5,
			"max" : 10},
	"MaxVolume" : { "command" : "SV1M",
				"response" : "([])"
			"min" : -95.5,
			"max" : 31.5},
	"MasterVolumeUp" : { "command" : "P1VMU",
				"response" : "([])"
			"min" : 0.5,
			"max" : 5},
	"MasterVolumeDown" : { "command" : "P1VMD",
				"response" : "([])"
			"min" : 0.5,
			"max" : 5},
	"VolumeFront" : { "command" : "P1VF",
			"min" : -10,
			"max" : 10},
	"VolumeCenter" : { "command" : "P1VC",
			"min" : -10,
			"max" : 10},
	"VolumeSurround" : { "command" : "P1VR",
			"min" : -10,
			"max" : 10},
	"VolumeBack" : { "command" : "P1VB",
			"min" : -10,
			"max" : 10},
	"VolumeSub" : { "command" : "P1VS",
			"min" : -30,
			"max" : 20},
	"VolumeLFE" : { "command" : "P1VL",
			"min" : -10,
			"max" : 0},
	"MasterBalance" : { "command" : "P1LM",
			"min" : -10,
			"max" : 10},
	"HeadphoneBalance" : { "command" : "HB",
			"min" : -12.5,
			"max" : 12.5},
	"BalanceFront" : { "command" : "P1LF",
			"min" : -10,
			"max" : 10},
	"BalanceSurround" : { "command" : "P1LR",
			"min" : -10,
			"max" : 10},
	"BalanceBack" : { "command" : "P1LB",
			"min" : -10,
			"max" : 10},
	"MasterBass" : { "command" : "P1BM",
			"min" : -12,
			"max" : 12},
	"HeadphoneBass" : { "command" : "HB",
			"min" : -14,
			"max" : 14},
	"BassFront" : { "command" : "P1BF",
			"min" : -12,
			"max" : 12},
	"BassCenter" : { "command" : "P1BC",
			"min" : -12,
			"max" : 12},
	"BassSurround" : { "command" : "P1BR",
			"min" : -12,
			"max" : 12},
	"BassRear" : { "command" : "P1BB",
			"min" : -12,
			"max" : 12},
	"MainTreble" : { "command" : "P1TM",
			"min" : -12,
			"max" : 12},
	"HeadphoneTreble" : { "command" : "HT",
			"min" : -14,
			"max" : 14},
	"TrebleFront" : { "command" : "P1TF",
			"min" : -12,
			"max" : 12},
	"TrebleCenter" : { "command" : "P1TC",
			"min" : -12,
			"max" : 12},
	"TrebleSurround" : { "command" : "P1TR",
			"min" : -12,
			"max" : 12},
	"TrebleRear" : { "command" : "P1TB",
			"min" : -12,
			"max" : 12},
	"Tone" : { "command" : "P1TE",
		   "values" : {"Bypass" : "0",
		   				"Enable" : "1"} },
	#TODO input-specific settings
		   				
	"Compression" : { "command" : "P1C",
		   "values" : {"Normal" : "0",
		   				"Reduced" : "1",
		   				"Night" : "2"} },
	"Status" : { "command" : "P1s"},
	"SourceSeek" : { "command" : "P1SS",
		   "values" : {"Next" : "+",
		   				"Prev" : "-"} },
	"SleepTimer" : { "command" : "P1Z",
		   "values" : {"Off" : "0",
		   				"Thirty" : "1",
		   				"Sixty" : "2",
		   				"Ninety" : "3"} },
	"DisplayMessage" : { "command" : "P1z",
		   "values" : {"Line1" : "1",
		   				"Line2" : "2"} },
		   				
							
	"" : { "command" : "",
		   "values" : {"" : "0",
		   				"" : "1",
		   				"" : "1"} },
	"" : { "command" : "",
			"min" : ,
			"max" : },
}
